# 01. 파이썬 기반의 머신러닝과 생태계 이해
## 01. 머신러닝의 개념
1) 머신러닝<br/>
① 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법<br/>
② 복잡한 조건, 규칙들이 다양한 형태로 결합하고 시시각각 변해 그를 관통하는 일정한 패턴을 찾기 어려운 경우 사용 (ex : 스팸메일 필터링)<br/>
③ 데이터 기반으로 통계적 신뢰도 강화, 다양한 수학적 기법으로 예측 오류 최소화 <br/>
④ 단점 : 데이터에 매우 의존적(Garbage in, Garbage out)

2) 머신러닝의 분류<br/>
① 지도학습 : 분류, 회귀 등<br/>
② 비지도학습 : 클러스터링, 차원축소 등<br/>
③ 강화학습

## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
1) 사이킷런 : 머신러닝 패키지<br/>
2) 넘파이 : 행렬/선형대수/통계 패키지 <br/>
3) 판다스 : 데이터 핸들링. 2차원 데이터 처리에 특화<br/>
4) 맷플롯립, 시본 : 시각화<br/>
5) 주피터 노트북 : 아이파이썬 지원 툴

## 03. 넘파이
1) nd.array() : 리스트 등의 인자를 입력받아 ndarray로 변환. shape 이용 시 ndarray의 차원 파악 가능

In [3]:
# numpy 모듈을 np로 임포트
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 1차원 array가 3개의 데이터를 가짐

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # 2차원 array가 2개의 행과 3개의 열로 구성

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) # 2차원 array가 1개의 행과 3개의 열로 구성

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


2) ndarray 데이터 타입<br/>
① 숫자 값(int, unsigned int, float, complex), 문자열 값, 불 값 모두 가능<br/>
② ndarray 내에서는 같은 데이터 타입만 가능<br/>
③ dtype으로 ndarray내의 데이터 타입 확인 가능<br/>
④ 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변환 시, 데이터 크기가 더 큰 타입으로 변환 일괄 적용<br/>
⑤ astype() : ndarray 내 데이터 타입 변경

In [4]:
list1 = [1,2,3]
print(type(list1)) 
array1 = np.array(list1) 
print(type(array1)) 
print(array1.dtype) 

# 다른 데이터 유형 섞여있는 리스트
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2.dtype) # 숫자형값보다 데이터 크기가 큰 문자열 값으로 변환

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int가 float64로 변환

<class 'list'>
<class 'numpy.ndarray'>
int64
<U21
[1. 2. 3.] float64


In [5]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


3) ndarray 생성<br/>
① arange() : 0부터 (함수인자-1)까지의 값을 1차원 ndarray로 생성<br/>
② zeros() : 튜플 형태의 shape값 입력하면 그 차원을 모두 0으로 채운 ndarray 반환<br/>
③ ones() : 튜플 형태의 shape값 입력하면 그 차원을 모두 1로 채운 ndarray 반환

In [8]:
# 0부터 stop 값인 10에서 1을 뺀 9까지의 값으로 구성된 1차원 ndarray 생성
sequence_array = np.arange(10) 
print(sequence_array) 
print(sequence_array.dtype, sequence_array.shape) 

# int32 0을 3행 2열로 채운 2차원 ndarray 생성
zero_array = np.zeros((3,2), dtype='int32') 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# 1을 3행 2열로 채운 2차원 ndarray 생성
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


4) reshape() <br/>
① ndarray의 차원 및 크기 변경<br/>
② () 안에 변환 원하는 크기 입력<br/>
③ 인자로 -1 적용 시 다른 인자에 맞춰서 shape 계산하여 변환



In [9]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(-1, 1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (10, 1)


In [10]:
# 차원 맞지 않아 에러 발생
array4 = array1.reshape(-1, 4)

ValueError: ignored

In [11]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


5) 인덱싱 <br/>
① 단일 인덱스
- 원하는 위치의 인덱스 값을 [] 안에 입력
- 1차원 및 다차원 ndarray에서 특정 데이터만 추출 가능
- 인덱스에 마이너스 기호 이용시 맨 뒤부터 데이터 추출
- ndarray 내의 데이터값 수정 가능


In [12]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = print(array1[2])
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0]) 
print('(row=0, col=1) index 가리키는 값:', array2d[0,1]) 
print('(row=1, col=0) index 가리키는 값:', array2d[1,0]) 
print('(row=2, col=2) index 가리키는 값:', array2d[1,1]) 

array1: [1 2 3 4 5 6 7 8 9]
3
value: None
<class 'NoneType'>
맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 5


② 슬라이싱(slicing)
- [시작 인덱스 : 종료인덱스] : 시작 인덱스에서 종료인덱스-1 까지 연속데이터 추출
- 시작, 종료 인덱스 생략 가능 : 시작 인덱스 생략시 맨 처음 인덱스인 0으로 간주, 종료 인덱스 생략시 맨 마지막 인덱스로 간주
- 2차원 ndarray에서 뒤에 오는 인덱스 없애면 1차원 ndarray 반환

In [14]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

print(array2d[0])
print(array2d[1])
print('array2d[0].shape:', array2d[0].shape, 'array2d[1].shape:', array2d[1].shape)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
[1 2 3]
[4 5 6]
array2d[0].shape: (3,) array2d[1].shape: (3,)


③ 팬시 인덱싱(fancy indexing)

- 리스트, ndarray로 인덱스 집합 지정 시 해당 위치의 ndarray 반환

In [15]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0,1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]] # 첫 번째, 두 번째 행의 모든 열 데이터 추출(열 위치는 따로 지정하지 않았기 때문)
print('array2d[[0, 1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


④ 불린 인덱싱(boolean indexing)

- [] 내에 조건문 지정
- 불린 인덱싱 동작 과정 : ndarray 필터링 조건 [] 내에 기재 → True 값에 해당하는 인덱스값만 저장 → 저장된 인덱스 데이터 세트로 ndarray 조회

In [16]:
array1d = np.arange(start=1, stop=10)
# [] 내에 array1d>5라는 불린 인덱싱 적용
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [19]:
# 그냥 조건문만 적으면 true/false ndarray 출력
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [21]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

#직접 인덱스 집합 만들어 대입한 것과 결과 동일
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


6) 행렬의 정렬<br/>
① np.sort() : 원행렬 유지한 상태에서 정렬한 행렬 반환<br/>
② ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환. 반환 값은 none<br/>
`* np.sort(), ndarray.sort() 모두 오름차순 정렬이 기본, 내림차순 정렬은 [::-1] 적용`

③ np.argsort() : 정렬된 행렬의 원본 행렬 인덱스를 ndarray로 반환

In [22]:
org_array = np.array([3,1,9,5])
print('원본 행렬 :', org_array)

# np.sort()로 org_array 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 org_array 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬 : [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [24]:
sort_array1_desc = np.sort(org_array[::-1])
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [1 3 5 9]


In [25]:
array2d = np.array([[8, 12], [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [26]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [27]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순 정렬 시 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순 정렬 시 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


7) 선형대수 연산

① np.dot() : 행렬 내적 계산<br/>
② np.transpose() : 전치 행렬 계산

In [28]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

C = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(C)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
