# 기초

## PyTorch 패키지 기본 구성
### 1. torch
- 메인 네임 스페이스
- 텐서 등 다양한 수학함수 포함
- Numpy와 유사한 구조

### 2. torch.autograd
- 자동 미분을 위한 함수 포함
  - Function : 자체 미분 가능 함수 정의 시 사용하는 기반 클래스
  - 콘텍스트 매니저(enable_grad/no_grad) : 자동 미분의 on/off 제어

### 3. torch.nn
- 신경망 구축 위한 다양한 데이터 구조, 레이어 등 정의
  - ex) RNN, LSTM, ReLu, MSELoss

### 4. torch. optim
  - 확률적 경사 하강법(SGD) 중심의 파라미터 최적화 알고리즘 구현

### 5. torch.utils.data
  - SGD의 반복 연산 실행 시 사용하는 미니 배치용 유틸리티 함수 포함

### 6. torch.onnx
  - ONNX : Open Neural Network Exchange
  - 모델 export 시 사용
  - 서로 다른 딥러닝 프레임워크 간 모델 공유시 사용

## 텐서 조작


### 텐서
- 1차원 값 : 벡터
- 2차원 값 : 행렬
  - batch size : 행의 크기
  - dim : 열의 크기
- 3차원 이상의의 값 : 텐서
  - batch size, dim에 height 추가가

## 파이토치 텐서 선언하기

In [1]:
# 토치 임포트
import torch

### 1D with PyTorch

In [2]:
# 1차원 텐서(=벡터) 생성

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [5]:
# 슬라이싱

print(t[0], t[1], t[-1]) # 인덱스
print(t[2:5], t[4:-1]) # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])


### 브로드캐스팅(Broadcasting)

크기 다른 행렬, 텐서에 대해 자동으로 크기를 맞춰 사칙연산을 수행하도록 하는 기능

In [7]:
# Vector + scalar

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

# m2를 [3, 3]으로 바꿔 연산
print(m1+m2)

tensor([[4., 5.]])


In [8]:
# Vector 간 연산에서 브로드캐스팅 적용

m1 = torch.FloatTensor([[1, 2]]) # 1*2
m2 = torch.FloatTensor([[3], [4]]) # 2*1

print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### 행렬 곱셈, 원소 별 곱셈
- 행렬 곱셈 : `.matmul`
- 원소 별 곱셈 : `.mul`

In [9]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [10]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 평균

In [11]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [12]:
# 2차원 행렬 평균 : 4개 원소 평균
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [13]:
# dim을 인자로 주는 경우

print(t.mean(dim=0))

tensor([2., 3.])


`dim=0` : 첫번째 차원(= 행)을 제거하겠다 <br/>
열의 차원을 보존하며 평균 연산

In [14]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


dim=1 : 두번째 차원(= 열)을 제거하겠다 <br/>
열을 제거하여 평균 연산

In [16]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


dim=-1 : 마지막 차원(= 열)을 제거하겠다 <br/>
열을 제거하여 평균 연산

### 덧셈
평균과 동일한 알고리즘

In [17]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [18]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max, ArgMax
- Max : 원소 中 최대값 return
- ArgMax : 최대값을 가진 원소의 인덱스 return

In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


In [20]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


max에 `dim`인자 주면 argmax도 함께 return <br/>


In [21]:
# argmax값만 return받고 싶은 경우 : return값에도 인덱스 부여

print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


### 뷰(View)
- numpy의 reshape와 같은 역할

In [23]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [24]:
print(ft.shape)

torch.Size([2, 2, 3])


In [25]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [26]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 스퀴즈(Squeeze)
- 차원이 1인 경우, 해당 차원 제거

In [27]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print('sqeeze 결과 :', ft.squeeze())
print('sqeeze 후 shape :', ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
sqeeze 결과 : tensor([0., 1., 2.])
sqeeze 후 shape : torch.Size([3])


### 언스퀴즈(Unsqueeze)
- 특정 위치에 1인 차원 추가


In [28]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [29]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [30]:
# View로 똑같은 내용 구현

print(ft.view(1, -1))
print(ft.view(1, -1).shape)


tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [31]:
# unsqueeze 인자로 1 할당

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 타입캐스팅

In [33]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [34]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### concatenate

-`torch.cat` : 늘릴 차원을 인자로 할당

In [35]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [36]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [37]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [38]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# 선형 회귀

## 비용함수
- 비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)

- 경사하강법 : 가장 기본적인 Optimizer 알고리즘


### 파이토치에서 선형회귀 구현하기

In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [40]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [41]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [43]:
# 편향도 0으로 초기화
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [44]:
# 가설 선언
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [45]:
# 비용함수 선언

cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [46]:
# 경사하강법 구현

optimizer = optim.SGD([W, b], lr=0.01)

In [47]:
# gradient를 0으로 초기화
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 

In [48]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

### 자동 미분(Autograd) 실습하기

In [49]:
# 임의의 스칼라 텐서 w 선언 : requires_grad=True 설정하여 w에 대한 미분값 저장
w = torch.tensor(2.0, requires_grad=True)

# 수식 정의
y = w**2
z = 2*y + 5

# backward() : 해당 수식의 w에 대한 기울기 계산
z.backward()

print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


### 다중선형회귀 구현하기

In [50]:
# x 3개 선언
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가중치 w, 편향 b 선언
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# 가설, 비용함수, 옵티마이저 선언 후 경사하강법 1000회 반복
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [51]:
# 가설을 행렬곱으로 정의하여 코드 수정

x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

### nn.Module로 선형회귀 구현
이미 구현되어 제공되는 함수 호출

#### 단순 선형회귀

In [52]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [53]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [54]:
# 단순 선형 회귀 모델 선언 및 초기화
model = nn.Linear(1,1)
print(list(model.parameters()))

# 옵티마이저 정의 : 경사하강법 SGD 사용, learning rate 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)  

# 전체 훈련 데이터에 대해 SGD 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

[Parameter containing:
tensor([[-0.2677]], requires_grad=True), Parameter containing:
tensor([-0.0109], requires_grad=True)]
Epoch    0/2000 Cost: 24.097153
Epoch  100/2000 Cost: 0.060585
Epoch  200/2000 Cost: 0.037438
Epoch  300/2000 Cost: 0.023134
Epoch  400/2000 Cost: 0.014296
Epoch  500/2000 Cost: 0.008834
Epoch  600/2000 Cost: 0.005459
Epoch  700/2000 Cost: 0.003373
Epoch  800/2000 Cost: 0.002084
Epoch  900/2000 Cost: 0.001288
Epoch 1000/2000 Cost: 0.000796
Epoch 1100/2000 Cost: 0.000492
Epoch 1200/2000 Cost: 0.000304
Epoch 1300/2000 Cost: 0.000188
Epoch 1400/2000 Cost: 0.000116
Epoch 1500/2000 Cost: 0.000072
Epoch 1600/2000 Cost: 0.000044
Epoch 1700/2000 Cost: 0.000027
Epoch 1800/2000 Cost: 0.000017
Epoch 1900/2000 Cost: 0.000010
Epoch 2000/2000 Cost: 0.000006


In [55]:
# 최적화 확인

# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9949]], grad_fn=<AddmmBackward0>)


정답인 8에 가까운 값이므로 최적화 된 것으로 간주

In [56]:
# 학습 후의 W와 b의 값을 출력

print(list(model.parameters()))

[Parameter containing:
tensor([[1.9971]], requires_grad=True), Parameter containing:
tensor([0.0067], requires_grad=True)]


#### 다중 선형 회귀

In [57]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [58]:
# 모델 선언 및 초기화
model = nn.Linear(3,1)

# 가중치 출력
print(list(model.parameters()))

# 옵티마이저 정의
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

# 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

[Parameter containing:
tensor([[-0.4607,  0.0124,  0.0936]], requires_grad=True), Parameter containing:
tensor([0.5281], requires_grad=True)]
Epoch    0/2000 Cost: 40761.429688
Epoch  100/2000 Cost: 5.048667
Epoch  200/2000 Cost: 4.813394
Epoch  300/2000 Cost: 4.590391
Epoch  400/2000 Cost: 4.379076
Epoch  500/2000 Cost: 4.178770
Epoch  600/2000 Cost: 3.988918
Epoch  700/2000 Cost: 3.808990
Epoch  800/2000 Cost: 3.638451
Epoch  900/2000 Cost: 3.476785
Epoch 1000/2000 Cost: 3.323546
Epoch 1100/2000 Cost: 3.178276
Epoch 1200/2000 Cost: 3.040588
Epoch 1300/2000 Cost: 2.910027
Epoch 1400/2000 Cost: 2.786245
Epoch 1500/2000 Cost: 2.668882
Epoch 1600/2000 Cost: 2.557631
Epoch 1700/2000 Cost: 2.452136
Epoch 1800/2000 Cost: 2.352127
Epoch 1900/2000 Cost: 2.257246
Epoch 2000/2000 Cost: 2.167309


In [59]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.7658]], grad_fn=<AddmmBackward0>)


152와 근사한 값 나와 최적화된 것으로 간주

In [60]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.4892, 0.6128, 0.8999]], requires_grad=True), Parameter containing:
tensor([0.5417], requires_grad=True)]


# 클래스로 파이토치 모델 구현

단순 선형회귀

In [61]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [66]:
model = LinearRegressionModel()

In [65]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [67]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 11.484162
Epoch  100/2000 Cost: 0.023951
Epoch  200/2000 Cost: 0.014800
Epoch  300/2000 Cost: 0.009145
Epoch  400/2000 Cost: 0.005651
Epoch  500/2000 Cost: 0.003492
Epoch  600/2000 Cost: 0.002158
Epoch  700/2000 Cost: 0.001334
Epoch  800/2000 Cost: 0.000824
Epoch  900/2000 Cost: 0.000509
Epoch 1000/2000 Cost: 0.000315
Epoch 1100/2000 Cost: 0.000194
Epoch 1200/2000 Cost: 0.000120
Epoch 1300/2000 Cost: 0.000074
Epoch 1400/2000 Cost: 0.000046
Epoch 1500/2000 Cost: 0.000028
Epoch 1600/2000 Cost: 0.000018
Epoch 1700/2000 Cost: 0.000011
Epoch 1800/2000 Cost: 0.000007
Epoch 1900/2000 Cost: 0.000004
Epoch 2000/2000 Cost: 0.000003


다중 선형 회귀

In [63]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [69]:
model = MultivariateLinearRegressionModel()

In [68]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [70]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 27948.765625
Epoch  100/2000 Cost: 0.490603
Epoch  200/2000 Cost: 0.486734
Epoch  300/2000 Cost: 0.483003
Epoch  400/2000 Cost: 0.479400
Epoch  500/2000 Cost: 0.475938
Epoch  600/2000 Cost: 0.472586
Epoch  700/2000 Cost: 0.469339
Epoch  800/2000 Cost: 0.466216
Epoch  900/2000 Cost: 0.463180
Epoch 1000/2000 Cost: 0.460251
Epoch 1100/2000 Cost: 0.457407
Epoch 1200/2000 Cost: 0.454653
Epoch 1300/2000 Cost: 0.451983
Epoch 1400/2000 Cost: 0.449391
Epoch 1500/2000 Cost: 0.446881
Epoch 1600/2000 Cost: 0.444436
Epoch 1700/2000 Cost: 0.442062
Epoch 1800/2000 Cost: 0.439746
Epoch 1900/2000 Cost: 0.437495
Epoch 2000/2000 Cost: 0.435308


# 커스텀 데이터 셋
- `torch.utils.data.Dataset`을 상속받아 직접 커스텀 데이터 셋 생성 가능
- `torch.utils.data.Dataset` : 파이토치에서 데이터셋을 제공하는 추상 클래스

```python
class CustomDataset(torch.utils.data.Dataset): 
  def __init__(self):
  # 데이터셋 전처리
  def __len__(self):
  # 데이터셋 길이 (= 총 샘플 수)
  def __getitem__(self, idx): 
  # 데이터셋에서 특정 1개의 샘플을 가져오는 함수
```

커스텀 데이터 셋으로 선형회귀 구현

In [72]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [73]:
# Dataset 상속
class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [74]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [75]:
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [76]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 16711.613281
Epoch    0/20 Batch 2/3 Cost: 5968.732910
Epoch    0/20 Batch 3/3 Cost: 2857.959229
Epoch    1/20 Batch 1/3 Cost: 403.177673
Epoch    1/20 Batch 2/3 Cost: 146.016876
Epoch    1/20 Batch 3/3 Cost: 26.508766
Epoch    2/20 Batch 1/3 Cost: 4.560556
Epoch    2/20 Batch 2/3 Cost: 18.331013
Epoch    2/20 Batch 3/3 Cost: 7.807921
Epoch    3/20 Batch 1/3 Cost: 2.040971
Epoch    3/20 Batch 2/3 Cost: 4.053217
Epoch    3/20 Batch 3/3 Cost: 2.856211
Epoch    4/20 Batch 1/3 Cost: 3.847189
Epoch    4/20 Batch 2/3 Cost: 2.195597
Epoch    4/20 Batch 3/3 Cost: 4.624246
Epoch    5/20 Batch 1/3 Cost: 4.077871
Epoch    5/20 Batch 2/3 Cost: 2.276790
Epoch    5/20 Batch 3/3 Cost: 4.486425
Epoch    6/20 Batch 1/3 Cost: 3.261948
Epoch    6/20 Batch 2/3 Cost: 4.151172
Epoch    6/20 Batch 3/3 Cost: 2.115610
Epoch    7/20 Batch 1/3 Cost: 1.262930
Epoch    7/20 Batch 2/3 Cost: 9.320280
Epoch    7/20 Batch 3/3 Cost: 0.355717
Epoch    8/20 Batch 1/3 Cost: 1.771634
Epoch    

In [77]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[154.3738]], grad_fn=<AddmmBackward0>)
